# Generated by Django 4.2.7 on 2023-11-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_rename_tag_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
