# Generated by Django 4.2.7 on 2023-11-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
