# Generated by Django 4.2.7 on 2023-11-27 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_alter_task_content_alter_task_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assignees",
        ),
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
