# Generated by Django 4.2.7 on 2023-11-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0008_alter_tag_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
