# Generated by Django 4.2.7 on 2023-11-27 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0010_alter_task_assignee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
    ]
