# Generated by Django 4.2.7 on 2023-12-07 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0011_remove_task_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "-created_at"]},
        ),
    ]
